grid_map_topic: /potential_field

grid_map_visualizations:

  - name: elevation_points
    type: point_cloud
    params:
     layer: potential_field

  - name: map_region
    type: map_region
    params:
     color: 3289650
     line_width: 0.003

  - name: potential_field_grid
    type: occupancy_grid
    params:
     layer: potential_field
     data_min: 0.08
     data_max: -0.16

  - name: elevation_cells
    type: grid_cells
    params:
     layer: potential_field
     lower_threshold: -0.08
     upper_threshold: 0.0
